services:
  aurora.coinly.api:
    image: ${DOCKER_REGISTRY-}aurora/coinly-api:1.0
    build:
      context: .
      dockerfile: src/Aurora.Coinly.Api/Dockerfile
    container_name: Aurora.Coinly.Api
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aurora.coinly.seq:5341/ingest/otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
        - aurora.coinly.database

  aurora.coinly.database:
    image: postgres:latest
    container_name: Aurora.Coinly.Postgres
    environment:
      - POSTGRES_DB=auroracoinly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  aurora.coinly.seq:
    image: datalust/seq:2024.3
    container_name: Aurora.Coinly.Seq
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341