global using Aurora.Coinly.Application.Abstractions.Authentication;
global using Aurora.Coinly.Application.Abstractions.Exceptions;
global using Aurora.Coinly.Application.Abstractions.Messaging;
global using Aurora.Coinly.Application.Abstractions.Time;
global using Aurora.Coinly.Domain.Abstractions;
global using Aurora.Coinly.Domain.Shared;
global using FluentValidation;
global using MediatR;
global using System.Text.Json.Serialization;